#!/usr/bin/env bash
#The file /etc/passwd has already been covered in a previous project and you shoulDbe familiar with it. Today we will make up a story based on it
while IFS=:  read -r username password userID groupID userIDinfo homedir shell
do
echo "The user $username is part of the $groupID gang, lives in $homedir and rides $shell. $userID's place is protected by the passcode $password, more info about the user here: $userIDinfo"
done < /etc/passwd
